### ISSUE TITLE
加入与创建社团功能

### ISSUE THREAD

**Issue by georgesha** [Tsingtuan/tsingtuan-frontend#10]
1. 如果大学->社团都已在数据库存在，直接加入
  - student table 增
  - position table 增
2. 如果大学不存在->创建大学+创建社团+加入
  - university table 增
  - organization table 增
  - student table 增
  - position table 增
3. 如果大学存在，社团不存在->创建社团+加入
  - organization table 增
  - student table 增
  - position table 增

**Comment by Xeonice** [comment]
@georgesha 认领任务
