### ISSUE TITLE
人事页面

### ISSUE THREAD

**Issue by georgesha** [Tsingtuan/tsingtuan-frontend#7]
![default](https://user-images.githubusercontent.com/15117015/45792439-bdf81c80-bc5b-11e8-89d8-1bc9c641da57.png)

**Comment by georgesha** [comment]
![default](https://user-images.githubusercontent.com/15117015/45792451-c6505780-bc5b-11e8-929c-33d446ef1763.png)

**Comment by Xeonice** [comment]
认领任务

**Comment by georgesha** [comment]
@Xeonice 人事页面有一个小问题，应该是点“人事安排”进入该页面，而不是点“我的”

**Comment by Xeonice** [comment]
@georgesha 已修复，请再次进行查阅
